/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiNegotiateRouteImport } from './routes/ai-negotiate'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as NegotiateRouteImport } from './routes/negotiate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiNegotiateRoute = AiNegotiateRouteImport.update({
  id: '/ai-negotiate',
  path: '/ai-negotiate',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NegotiateRoute = NegotiateRouteImport.update({
  id: '/negotiate',
  path: '/negotiate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-negotiate': typeof AiNegotiateRoute
  '/catalog': typeof CatalogRoute
  '/dashboard': typeof DashboardRoute
  '/negotiate': typeof NegotiateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-negotiate': typeof AiNegotiateRoute
  '/catalog': typeof CatalogRoute
  '/dashboard': typeof DashboardRoute
  '/negotiate': typeof NegotiateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-negotiate': typeof AiNegotiateRoute
  '/catalog': typeof CatalogRoute
  '/dashboard': typeof DashboardRoute
  '/negotiate': typeof NegotiateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-negotiate' | '/catalog' | '/dashboard' | '/negotiate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-negotiate' | '/catalog' | '/dashboard' | '/negotiate'
  id:
    | '__root__'
    | '/'
    | '/ai-negotiate'
    | '/catalog'
    | '/dashboard'
    | '/negotiate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiNegotiateRoute: typeof AiNegotiateRoute
  CatalogRoute: typeof CatalogRoute
  DashboardRoute: typeof DashboardRoute
  NegotiateRoute: typeof NegotiateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-negotiate': {
      id: '/ai-negotiate'
      path: '/ai-negotiate'
      fullPath: '/ai-negotiate'
      preLoaderRoute: typeof AiNegotiateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negotiate': {
      id: '/negotiate'
      path: '/negotiate'
      fullPath: '/negotiate'
      preLoaderRoute: typeof NegotiateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiNegotiateRoute: AiNegotiateRoute,
  CatalogRoute: CatalogRoute,
  DashboardRoute: DashboardRoute,
  NegotiateRoute: NegotiateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
